"""add_admin_action_log

Revision ID: 2705bdea66c5
Revises: 37df8a3b0c6e
Create Date: 2025-12-04 21:20:22.000928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2705bdea66c5'
down_revision = '37df8a3b0c6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_action_log_action'), 'admin_action_log', ['action'], unique=False)
    op.create_index(op.f('ix_admin_action_log_id'), 'admin_action_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_action_log_id'), table_name='admin_action_log')
    op.drop_index(op.f('ix_admin_action_log_action'), table_name='admin_action_log')
    op.drop_table('admin_action_log')
    # ### end Alembic commands ###
