"""add_admin_2fa_table

Revision ID: 37df8a3b0c6e
Revises: d180bd20f471
Create Date: 2025-12-04 21:14:19.442866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37df8a3b0c6e'
down_revision = 'd180bd20f471'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_2fa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_admin_2fa_id'), 'admin_2fa', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_2fa_id'), table_name='admin_2fa')
    op.drop_table('admin_2fa')
    # ### end Alembic commands ###
